
package client.client_generated;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ThrottlingException", targetNamespace = "http://server/")
public class ThrottlingException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ThrottlingFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ThrottlingException(String message, ThrottlingFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ThrottlingException(String message, ThrottlingFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.client_generated.ThrottlingFault
     */
    public ThrottlingFault getFaultInfo() {
        return faultInfo;
    }

}
